name: CI/CD for Docarized Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:  # Changed from 'job' to 'jobs'
  build-and-test:  # Fixed job name format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t flask-app .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 flask-app
    
  build-and-publish:  # Fixed job name format
    needs: build-and-test  # Updated to match the job name above
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
        
      - name: Build and push Docker image  # Fixed spacing and dash
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
        
      - name: Image Digest  # Fixed spacing and dash
        run: echo ${{ steps.build_and_push.outputs.digest }}
        